### ISSUE TITLE
Is there a vignette? Can not figure out how should the data be structured.

### ISSUE THREAD

**Issue by lix2k3** [ricoderks/Rcpm#11]
What does I x K by J mean for the X data frame that should be supplied to MSCA?

I have been trying to run this but not sure how to create such a (three-dimensional) matrix of observations. In my dataframe, individuals are in rows and the variables in columns, whereas the repeated measurements are long (column-wise).  Please advise.

**Comment by ricoderks** [comment]
Hi,

I got this code from a former collega years ago. I checked my old code on how I used it. The matrix needs to have the variables in the columns and the individuals in the rows. A repeated measurement is an extra row.

Cheers, Rico

**Comment by lix2k3** [comment]
Appreciate it! I got it to work.  It appears the line nPCS = K is where it stalls.  It's asking for a number of pPCA components that's equal to the number of rows in the dataframe which will always throw an error.  I think it should probably be nPCS = I.

I would attempt to add a commit, but such GIT a newbie.  I'd have to be walked through it.

**Comment by ricoderks** [comment]
That's weird. In my old code it runs without any problem. Because I'am not the original author of the code and it still works in my case I would like to leave the code  as it is. I'll try to see if I can reach the original author.

Cheers, Rico

**Comment by ricoderks** [comment]
Closing for now. Feel free to open if needed!
